### ISSUE TITLE
Não consigo criar as tabelas pelo através do spring boot:

### ISSUE THREAD

**Issue by cami-la** [igor-rocha-oliveira/academia.digital#1]
Oi, @igor-rocha-oliveira. Tudo bem?
Tenta fazer o seguinte, no arquivo de configuração `application.yml`:

**É ddl-auto, ok? No seu arquivo está dll-auto.**

```
jpa:
    show-sql: true
    generate-dll: true
    hibernate:
      ddl-auto: create-drop
    proprieties:
      hibernate.format_sql: true
```

1. Troca a propriedade do `ddl-auto` do hibernate para `create-drop`.
2. Roda novamente a aplicação
3. Confere se agora ele criou as tabelas
4. Caso sim, volta para o `ddl-aulto: update`
5. Roda o projeto novamente

Me fala se funcionou! (:
